### ISSUE TITLE
config file and models trained on fastMRI dataset 

### ISSUE THREAD

**Issue by chuan1093** [tinyRattar/CSMRI_0325#3]
Would you please upload your **config file** of training on **fastMRI dataset**?
It would be better if you could upload your **models** trained on **fastMRI dataset**!

Thanks a lot!

**Comment by tinyRattar** [comment]
I have upload the config file in the folder.
Core will use 12 as the data range for PSNR in fastMRI dataset.
The data range is estimated by myself, so maybe you should check it.
The PSNR seems not good (about 20+db), but the visual result seems no problem.

I also upload the result folder of FastMRI in [CDDNwithTDC_storage](https://github.com/tinyRattar/CDDNwithTDC_storage) as well.
If you want to evaluate, remember use `core.loadCkpt(300, False)` instead of `core.loadCkpt(1000, True)` as they converge within 300 epoch.

Sorry for late reply.
